version: 1.0.{build}-{branch}

environment:
  matrix:
    - RUBY_VERSION: 23
    - RUBY_VERSION: 22

branches:
  only:
  - master

skip_tags: true


cache:
  - vendor/bundle

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - SET SSL_CERT_FILE=C:/ruby24-x64/ssl/cert.pem
  - bundle env
  - bundle check || bundle install --path=vendor/bundle --retry=3 --jobs=3
  - bundle clean --force

before_test:
  - ruby -v
  - gem -v
  - bundle -v

build: off

test_script:
  - bundle exec rake